name: pre-comAGPL-3

on:
  pull_request:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  pre-comAGPL-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-comAGPL-3/action@v2.0.0
